export const CHART_KEYS = {
  BAR: 'BarChart',
  LINE: 'LineChart',
  AREA: 'AreaChart',
  PIE: 'PieChart',
  SCATTER: 'ScatterChart',
  EFFECT_SCATTER: 'EffectScatterChart',
  RADAR: 'RadarChart',
  TREE: 'TreeChart',
  TREEMAP: 'TreemapChart',
  SUNBURST: 'SunburstChart',
  BOXPLOT: 'BoxplotChart',
  CANDLESTICK: 'CandlestickChart',
  HEATMAP: 'HeatmapChart',
  PARALLEL: 'ParallelChart',
  GRAPH: 'GraphChart',
  SANKEY: 'SankeyChart',
  FUNNEL: 'FunnelChart',
  GAUGE: 'GaugeChart',
  THEME_RIVER: 'ThemeRiverChart',
} as const;
